-- CREATE TABLE users(
--     usrId serial primary key,
--     usrName varchar(25) not null,
--     usrEmail varchar(50) not null unique,
--     usrPassword varchar(255) not null,
--     usrDescription varchar(500),
--     usrProfileLink varchar(1000),
--     usrPhoneNumber varchar(18),
--     isEnabled boolean,
--     isEmailVerified boolean,
--     isPhoneNumberVerified boolean,
--     loginProviderType varchar(25),
--     loginProviderUserId varchar(255)

-- );